# -*- coding: utf-8 -*-
"""ExpenseTrackerCli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cp2bvMtQPthGn-K-gZBWalFydoe5NpEk
"""

import csv
import os
from datetime import datetime

FILE_NAME = "expenses.csv"

# -------- Create the CSV file if missing --------
def initialize_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "Type", "Category", "Amount"])
        print("Created expenses.csv")

# -------- Add Entry --------
def add_entry(entry_type, category, amount):
    date = datetime.now().strftime("%Y-%m-%d")
    with open(FILE_NAME, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([date, entry_type, category, amount])
    print("Entry added successfully!\n")

# -------- View All Records --------
def view_records():
    print("\n--- All Records ---")
    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)
    print()

# -------- Monthly Summary --------
def monthly_summary(month, year):
    total_income = 0
    total_expense = 0

    with open(FILE_NAME, "r") as file:
        reader = csv.DictReader(file)
        for row in reader:
            if row["Date"][5:7] == month and row["Date"][0:4] == year:
                if row["Type"] == "income":
                    total_income += float(row["Amount"])
                else:
                    total_expense += float(row["Amount"])

    print(f"Total Income  : {total_income}")
    print(f"Total Expense : {total_expense}")
    print(f"Savings       : {total_income - total_expense}\n")

# -------- Interactive Menu for Colab --------
def menu():
    initialize_file()

    while True:
        print("===== Expense Tracker (Colab Mode) =====")
        print("1. Add Entry")
        print("2. View All Records")
        print("3. Monthly Summary")
        print("4. Exit")

        choice = input("Enter choice (1-4): ")

        if choice == "1":
            t = input("Type (income/expense): ").lower()
            c = input("Category: ")
            a = float(input("Amount: "))
            add_entry(t, c, a)

        elif choice == "2":
            view_records()

        elif choice == "3":
            m = input("Month (MM): ")
            y = input("Year (YYYY): ")
            monthly_summary(m, y)

        elif choice == "4":
            print("Exiting...")
            break

        else:
            print("Invalid option!\n")

menu()